export interface GenreDefinition {
  id: string;
  name: string;
  category: 'core' | 'indian' | 'style';
  description: string;
  iconName: string;
  gradient: {
    from: string;
    to: string;
    glow: string;
  };
  featured: boolean; // Top 20-25 major genres displayed first
  popularLanguages?: string[];
  searchQuery?: string;
}

export const GENRE_CATALOG: GenreDefinition[] = [
  // ── 1. CORE GLOBAL GENRES ──────────────────────────────────────────────
  {
    id: 'pop',
    name: 'Pop',
    category: 'core',
    description: 'Catchy hooks, vibrant synths, and chart-topping melodies',
    iconName: 'Sparkles',
    gradient: { from: '#FF2E93', to: '#FF8A00', glow: 'rgba(255, 46, 147, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi', 'Telugu', 'Tamil', 'Punjabi', 'Korean'],
    searchQuery: 'Pop Songs Hits',
  },
  {
    id: 'rock',
    name: 'Rock',
    category: 'core',
    description: 'Electric riffs, powerful drums, and classic anthems',
    iconName: 'Flame',
    gradient: { from: '#E50914', to: '#7928CA', glow: 'rgba(229, 9, 20, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi', 'Tamil', 'Bengali'],
    searchQuery: 'Rock Songs Classics',
  },
  {
    id: 'hiphop',
    name: 'Hip-Hop / Rap',
    category: 'core',
    description: 'Heavy basslines, rapid flow, and street rhythms',
    iconName: 'Mic',
    gradient: { from: '#F59E0B', to: '#D97706', glow: 'rgba(245, 158, 11, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi', 'Punjabi', 'Tamil', 'Telugu'],
    searchQuery: 'Hip Hop Rap Beats',
  },
  {
    id: 'rnb',
    name: 'R&B / Soul',
    category: 'core',
    description: 'Velvety vocals, smooth grooves, and heartfelt emotion',
    iconName: 'Heart',
    gradient: { from: '#EC4899', to: '#8B5CF6', glow: 'rgba(236, 72, 153, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi'],
    searchQuery: 'RnB Soul Music',
  },
  {
    id: 'electronic',
    name: 'Electronic / EDM',
    category: 'core',
    description: 'Pulsing synths, festival drops, and dancefloor energy',
    iconName: 'Zap',
    gradient: { from: '#06B6D4', to: '#3B82F6', glow: 'rgba(6, 182, 212, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi', 'Telugu', 'Tamil'],
    searchQuery: 'EDM Electronic Dance',
  },
  {
    id: 'dance',
    name: 'Dance',
    category: 'core',
    description: 'High-tempo club beats and unstoppable party rhythms',
    iconName: 'Activity',
    gradient: { from: '#10B981', to: '#06B6D4', glow: 'rgba(16, 185, 129, 0.35)' },
    featured: true,
    popularLanguages: ['Hindi', 'Telugu', 'Tamil', 'Punjabi', 'English'],
    searchQuery: 'Dance Party Hits',
  },
  {
    id: 'jazz',
    name: 'Jazz',
    category: 'core',
    description: 'Improvisational brass, swing chords, and lounge vibes',
    iconName: 'Music2',
    gradient: { from: '#D97706', to: '#B45309', glow: 'rgba(217, 119, 6, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi'],
    searchQuery: 'Jazz Classics Chill',
  },
  {
    id: 'blues',
    name: 'Blues',
    category: 'core',
    description: 'Expressive guitar bends, soul lamentations, and blues scales',
    iconName: 'Disc',
    gradient: { from: '#3B82F6', to: '#1D4ED8', glow: 'rgba(59, 130, 246, 0.35)' },
    featured: false,
    popularLanguages: ['English'],
    searchQuery: 'Blues Guitar Music',
  },
  {
    id: 'classical_global',
    name: 'Classical',
    category: 'core',
    description: 'Orchestral symphonies, piano concertos, and timeless masterworks',
    iconName: 'Award',
    gradient: { from: '#8B5CF6', to: '#6D28D9', glow: 'rgba(139, 92, 246, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Global'],
    searchQuery: 'Classical Orchestra Masterpieces',
  },
  {
    id: 'folk_global',
    name: 'Folk',
    category: 'core',
    description: 'Acoustic storytelling, native instruments, and rustic harmonies',
    iconName: 'Compass',
    gradient: { from: '#84CC16', to: '#65A30D', glow: 'rgba(132, 204, 22, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Hindi', 'Kannada', 'Tamil', 'Punjabi', 'English'],
    searchQuery: 'Folk Acoustic Traditional',
  },
  {
    id: 'country',
    name: 'Country',
    category: 'core',
    description: 'Twangy acoustics, storytelling ballads, and southern roots',
    iconName: 'Sun',
    gradient: { from: '#F97316', to: '#EA580C', glow: 'rgba(249, 115, 22, 0.35)' },
    featured: false,
    popularLanguages: ['English'],
    searchQuery: 'Country Hits Ballads',
  },
  {
    id: 'reggae',
    name: 'Reggae',
    category: 'core',
    description: 'Offbeat skank guitars, dub basslines, and island warmth',
    iconName: 'Radio',
    gradient: { from: '#22C55E', to: '#EAB308', glow: 'rgba(34, 197, 94, 0.35)' },
    featured: false,
    popularLanguages: ['English'],
    searchQuery: 'Reggae Roots Chill',
  },
  {
    id: 'metal',
    name: 'Metal',
    category: 'core',
    description: 'Heavy distortion, blistering solos, and aggressive intensity',
    iconName: 'Shield',
    gradient: { from: '#475569', to: '#0F172A', glow: 'rgba(71, 85, 105, 0.35)' },
    featured: false,
    popularLanguages: ['English', 'Hindi'],
    searchQuery: 'Heavy Metal Rock',
  },
  {
    id: 'alternative',
    name: 'Alternative',
    category: 'core',
    description: 'Post-grunge experimentation, emotive lyrics, and gritty guitars',
    iconName: 'Layers',
    gradient: { from: '#6366F1', to: '#4338CA', glow: 'rgba(99, 102, 241, 0.35)' },
    featured: false,
    popularLanguages: ['English', 'Hindi'],
    searchQuery: 'Alternative Rock Hits',
  },
  {
    id: 'indie',
    name: 'Indie',
    category: 'core',
    description: 'Authentic independent artistry, dreamy textures, and DIY spirit',
    iconName: 'Feather',
    gradient: { from: '#14B8A6', to: '#0D9488', glow: 'rgba(20, 184, 166, 0.35)' },
    featured: true,
    popularLanguages: ['Hindi', 'English', 'Telugu', 'Tamil', 'Malayalam'],
    searchQuery: 'Indie Music Discoveries',
  },
  {
    id: 'lofi',
    name: 'Lo-fi',
    category: 'core',
    description: 'Mellow beats, vinyl crackles, and relaxed study companions',
    iconName: 'Coffee',
    gradient: { from: '#A855F7', to: '#6366F1', glow: 'rgba(168, 85, 247, 0.35)' },
    featured: true,
    popularLanguages: ['Hindi', 'Telugu', 'Tamil', 'English'],
    searchQuery: 'Lofi Chill Study Beats',
  },
  {
    id: 'ambient',
    name: 'Ambient',
    category: 'core',
    description: 'Atmospheric drones, soundscapes, and calming spacious sound',
    iconName: 'Cloud',
    gradient: { from: '#0284C7', to: '#0369A1', glow: 'rgba(2, 132, 199, 0.35)' },
    featured: false,
    popularLanguages: ['English', 'Global'],
    searchQuery: 'Ambient Sleep Soundscapes',
  },
  {
    id: 'instrumental',
    name: 'Instrumental',
    category: 'core',
    description: 'Pure acoustic and electric arrangements with no vocals',
    iconName: 'Volume2',
    gradient: { from: '#64748B', to: '#334155', glow: 'rgba(100, 116, 139, 0.35)' },
    featured: false,
    popularLanguages: ['Telugu', 'Hindi', 'Tamil', 'Global'],
    searchQuery: 'Instrumental Covers Flute Violin',
  },
  {
    id: 'devotional_global',
    name: 'Devotional & Spiritual',
    category: 'core',
    description: 'Sacred chants, meditative prayers, and divine tranquility',
    iconName: 'SunMedium',
    gradient: { from: '#F59E0B', to: '#B45309', glow: 'rgba(245, 158, 11, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Hindi', 'Tamil', 'Kannada', 'Sanskrit'],
    searchQuery: 'Devotional Songs Bhakti Stotram',
  },
  {
    id: 'world',
    name: 'World Music',
    category: 'core',
    description: 'Traditional rhythms from across continents and cultural heritage',
    iconName: 'Globe',
    gradient: { from: '#10B981', to: '#047857', glow: 'rgba(16, 185, 129, 0.35)' },
    featured: false,
    popularLanguages: ['Global', 'Hindi', 'Arabic', 'Spanish'],
    searchQuery: 'World Music Heritage',
  },

  // ── 2. INDIAN-FOCUSED GENRES ──────────────────────────────────────────
  {
    id: 'indian_pop',
    name: 'Indian Pop',
    category: 'indian',
    description: 'Modern Indian non-film singles, independent hits, and viral tracks',
    iconName: 'Sparkles',
    gradient: { from: '#FA233B', to: '#EC4899', glow: 'rgba(250, 35, 59, 0.35)' },
    featured: true,
    popularLanguages: ['Hindi', 'Punjabi', 'Telugu', 'Tamil', 'Kannada'],
    searchQuery: 'Indian Pop Hits I-Pop',
  },
  {
    id: 'indian_classical',
    name: 'Indian Classical',
    category: 'indian',
    description: 'Ancient ragas, intricate talas, and spiritual acoustic mastery',
    iconName: 'Crown',
    gradient: { from: '#D97706', to: '#92400E', glow: 'rgba(217, 119, 6, 0.35)' },
    featured: true,
    popularLanguages: ['Sanskrit', 'Telugu', 'Hindi', 'Tamil', 'Kannada'],
    searchQuery: 'Indian Classical Ragas',
  },
  {
    id: 'carnatic',
    name: 'Carnatic',
    category: 'indian',
    description: 'South Indian classical system rich in kritis, swaras, and varnams',
    iconName: 'Sparkles',
    gradient: { from: '#B45309', to: '#78350F', glow: 'rgba(180, 83, 9, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Tamil', 'Kannada', 'Sanskrit', 'Malayalam'],
    searchQuery: 'Carnatic Classical Vocal Instrumental',
  },
  {
    id: 'hindustani',
    name: 'Hindustani Classical',
    category: 'indian',
    description: 'North Indian classical tradition featuring khyal, dhrupad, and sitar',
    iconName: 'Music',
    gradient: { from: '#9333EA', to: '#581C87', glow: 'rgba(147, 51, 234, 0.35)' },
    featured: true,
    popularLanguages: ['Hindi', 'Sanskrit', 'Bengali', 'Marathi'],
    searchQuery: 'Hindustani Classical Sitar Sarod Vocal',
  },
  {
    id: 'bollywood',
    name: 'Bollywood',
    category: 'indian',
    description: 'Grand cinematic soundtracks, chartbusters, and romantic duets',
    iconName: 'Film',
    gradient: { from: '#E50914', to: '#DC2626', glow: 'rgba(229, 9, 20, 0.38)' },
    featured: true,
    popularLanguages: ['Hindi', 'Punjabi', 'Urdu'],
    searchQuery: 'Bollywood Hits Soundtrack',
  },
  {
    id: 'indian_folk',
    name: 'Indian Folk',
    category: 'indian',
    description: 'Rustic regional songs celebrating harvest, soil, and folklore',
    iconName: 'Compass',
    gradient: { from: '#EAB308', to: '#CA8A04', glow: 'rgba(234, 179, 8, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Hindi', 'Kannada', 'Tamil', 'Punjabi', 'Rajasthani', 'Bhojpuri'],
    searchQuery: 'Indian Folk Songs Traditional',
  },
  {
    id: 'filmi',
    name: 'Filmi / Cinema',
    category: 'indian',
    description: 'South Indian and Pan-India cinematic orchestral scores & mass songs',
    iconName: 'Tv',
    gradient: { from: '#FF1E27', to: '#7C3AED', glow: 'rgba(255, 30, 39, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Tamil', 'Kannada', 'Malayalam', 'Hindi'],
    searchQuery: 'Cinema Movie Songs Hits',
  },
  {
    id: 'ghazal',
    name: 'Ghazal',
    category: 'indian',
    description: 'Poetic couplets of love, longing, and philosophical introspection',
    iconName: 'BookOpen',
    gradient: { from: '#0284C7', to: '#1E3A8A', glow: 'rgba(2, 132, 199, 0.35)' },
    featured: true,
    popularLanguages: ['Urdu', 'Hindi', 'Punjabi'],
    searchQuery: 'Ghazal Jagjit Singh Mehdi Hassan',
  },
  {
    id: 'qawwali',
    name: 'Qawwali',
    category: 'indian',
    description: 'High-energy Sufi devotional music driven by harmonium and handclaps',
    iconName: 'Mic2',
    gradient: { from: '#DC2626', to: '#7F1D1D', glow: 'rgba(220, 38, 38, 0.35)' },
    featured: false,
    popularLanguages: ['Urdu', 'Punjabi', 'Hindi'],
    searchQuery: 'Qawwali Nusrat Fateh Ali Khan',
  },
  {
    id: 'sufi',
    name: 'Sufi',
    category: 'indian',
    description: 'Soulful mystical poetry seeking divine communion and ecstasy',
    iconName: 'Moon',
    gradient: { from: '#7C3AED', to: '#4C1D95', glow: 'rgba(124, 58, 237, 0.35)' },
    featured: true,
    popularLanguages: ['Hindi', 'Punjabi', 'Urdu'],
    searchQuery: 'Sufi Soul Music',
  },
  {
    id: 'bhajan',
    name: 'Bhajan',
    category: 'indian',
    description: 'Devotional hymns and stutis honoring divine deities with reverence',
    iconName: 'Sun',
    gradient: { from: '#F59E0B', to: '#D97706', glow: 'rgba(245, 158, 11, 0.35)' },
    featured: false,
    popularLanguages: ['Hindi', 'Telugu', 'Tamil', 'Kannada', 'Gujarati', 'Marathi'],
    searchQuery: 'Bhajan Aarti Devotional',
  },
  {
    id: 'bhangra',
    name: 'Bhangra',
    category: 'indian',
    description: 'High-octane Punjabi dhol beats, festive boliyan, and vibrant dance',
    iconName: 'Activity',
    gradient: { from: '#F97316', to: '#C2410C', glow: 'rgba(249, 115, 22, 0.35)' },
    featured: true,
    popularLanguages: ['Punjabi', 'Hindi'],
    searchQuery: 'Bhangra Dhol Punjabi Dance',
  },
  {
    id: 'garba',
    name: 'Garba & Dandiya',
    category: 'indian',
    description: 'Navratri circular dance rhythms, upbeat dholaks, and festive claps',
    iconName: 'Sparkles',
    gradient: { from: '#E11D48', to: '#BE123C', glow: 'rgba(225, 29, 72, 0.35)' },
    featured: false,
    popularLanguages: ['Gujarati', 'Hindi'],
    searchQuery: 'Garba Dandiya Navratri Hits',
  },
  {
    id: 'rabindra',
    name: 'Rabindra Sangeet',
    category: 'indian',
    description: 'Poetic compositions of Nobel laureate Rabindranath Tagore',
    iconName: 'Feather',
    gradient: { from: '#0D9488', to: '#115E59', glow: 'rgba(13, 148, 136, 0.35)' },
    featured: false,
    popularLanguages: ['Bengali', 'Hindi'],
    searchQuery: 'Rabindra Sangeet Classics',
  },
  {
    id: 'kuthu',
    name: 'Kuthu / Mass Beats',
    category: 'indian',
    description: 'Frenetic South Indian percussion, dappan kuthu, and theatre-shaking bass',
    iconName: 'Flame',
    gradient: { from: '#FF1E27', to: '#B91C1C', glow: 'rgba(255, 30, 39, 0.4)' },
    featured: true,
    popularLanguages: ['Tamil', 'Telugu', 'Kannada', 'Malayalam'],
    searchQuery: 'Kuthu Mass Beats Dance Tamil Telugu',
  },
  {
    id: 'gaana',
    name: 'Gaana',
    category: 'indian',
    description: 'Fast-paced rhythmic Tamil street ballads with honest lyrics',
    iconName: 'Radio',
    gradient: { from: '#0284C7', to: '#075985', glow: 'rgba(2, 132, 199, 0.35)' },
    featured: false,
    popularLanguages: ['Tamil'],
    searchQuery: 'Gaana Tamil Street Hits',
  },
  {
    id: 'lavani',
    name: 'Lavani',
    category: 'indian',
    description: 'Traditional Maharashtrian rhythmic dholki folk dance and song',
    iconName: 'Sparkles',
    gradient: { from: '#DB2777', to: '#9D174D', glow: 'rgba(219, 39, 119, 0.35)' },
    featured: false,
    popularLanguages: ['Marathi', 'Hindi'],
    searchQuery: 'Lavani Marathi Folk',
  },
  {
    id: 'baul',
    name: 'Baul',
    category: 'indian',
    description: 'Mystic Bengali folk troubadours with ektara and dotara',
    iconName: 'Compass',
    gradient: { from: '#CA8A04', to: '#854D0E', glow: 'rgba(202, 138, 4, 0.35)' },
    featured: false,
    popularLanguages: ['Bengali'],
    searchQuery: 'Baul Bengali Mystic Folk',
  },

  // ── 3. MUSIC STYLES & MOODS ──────────────────────────────────────────
  {
    id: 'melody',
    name: 'Melody',
    category: 'style',
    description: 'Sweet acoustic chord progressions, soulful flute, and lush orchestrations',
    iconName: 'Heart',
    gradient: { from: '#EC4899', to: '#BE185D', glow: 'rgba(236, 72, 153, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Tamil', 'Malayalam', 'Kannada', 'Hindi'],
    searchQuery: 'Soulful Melody Hits',
  },
  {
    id: 'romantic',
    name: 'Romantic',
    category: 'style',
    description: 'Love ballads, tender duets, and heartfelt cinematic confessions',
    iconName: 'HeartHandshake',
    gradient: { from: '#E11D48', to: '#9F1239', glow: 'rgba(225, 29, 72, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Hindi', 'Tamil', 'Kannada', 'Malayalam', 'Punjabi'],
    searchQuery: 'Romantic Love Songs',
  },
  {
    id: 'acoustic',
    name: 'Acoustic',
    category: 'style',
    description: 'Unamplified acoustic guitars, warm piano, and organic vocals',
    iconName: 'Guitar',
    gradient: { from: '#D97706', to: '#B45309', glow: 'rgba(217, 119, 6, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi', 'Telugu', 'Tamil'],
    searchQuery: 'Acoustic Guitar Sessions',
  },
  {
    id: 'unplugged',
    name: 'Unplugged & Live',
    category: 'style',
    description: 'Stripped-down live studio takes, concert ambiance, and raw acoustics',
    iconName: 'Mic',
    gradient: { from: '#8B5CF6', to: '#6D28D9', glow: 'rgba(139, 92, 246, 0.35)' },
    featured: false,
    popularLanguages: ['Hindi', 'Telugu', 'English', 'Tamil'],
    searchQuery: 'Unplugged Live Studio Sessions',
  },
  {
    id: 'soundtrack',
    name: 'Soundtrack / OST',
    category: 'style',
    description: 'Original film scores, heroic themes, and emotional cinematic queues',
    iconName: 'Film',
    gradient: { from: '#3B82F6', to: '#1D4ED8', glow: 'rgba(59, 130, 246, 0.35)' },
    featured: true,
    popularLanguages: ['Telugu', 'Hindi', 'Tamil', 'Kannada', 'English'],
    searchQuery: 'Original Soundtrack OST Themes',
  },
  {
    id: 'lullabies',
    name: 'Lullabies & Kids',
    category: 'style',
    description: 'Gentle night melodies, sweet rhymes, and soothing sleep songs',
    iconName: 'Moon',
    gradient: { from: '#38BDF8', to: '#0284C7', glow: 'rgba(56, 189, 248, 0.35)' },
    featured: false,
    popularLanguages: ['Telugu', 'Hindi', 'Tamil', 'English'],
    searchQuery: 'Lullaby Sleep Songs Babies Kids',
  },
  {
    id: 'meditation',
    name: 'Meditation & Yoga',
    category: 'style',
    description: 'Om chants, singing bowls, 432Hz healing sound, and mindful breath',
    iconName: 'SunMedium',
    gradient: { from: '#10B981', to: '#059669', glow: 'rgba(16, 185, 129, 0.35)' },
    featured: true,
    popularLanguages: ['Sanskrit', 'Global', 'Hindi', 'Telugu'],
    searchQuery: 'Meditation Yoga Om Chants 432Hz',
  },
  {
    id: 'chill',
    name: 'Chill & Relax',
    category: 'style',
    description: 'Smooth downtempo, cozy coffeehouse grooves, and stress relief',
    iconName: 'Coffee',
    gradient: { from: '#6366F1', to: '#4F46E5', glow: 'rgba(99, 102, 241, 0.35)' },
    featured: true,
    popularLanguages: ['English', 'Hindi', 'Telugu', 'Tamil'],
    searchQuery: 'Chill Relaxing Downtempo',
  },
];

export const POPULAR_GENRES = GENRE_CATALOG.filter(g => g.featured);

export function getGenreById(id: string): GenreDefinition | undefined {
  return GENRE_CATALOG.find(g => g.id.toLowerCase() === id.toLowerCase());
}
